SELECT
    ri.REST_ID AS REST_ID,
    ri.REST_NAME AS REST_NAME,
    ri.FOOD_TYPE AS FOOD_TYPE,
    ri.FAVORITES AS FAVORITES,
    ri.ADDRESS AS ADDRESS,
    rr.SCORE AS SCORE
FROM
    REST_INFO AS ri
INNER JOIN
    (
        SELECT
            REST_ID,
            ROUND(AVG(REVIEW_SCORE),2) AS SCORE
        FROM
            REST_REVIEW
        GROUP BY
            REST_ID
    ) AS rr
ON
    ri.REST_ID = rr.REST_ID
WHERE
    ri.ADDRESS LIKE '서울%'
ORDER BY
    SCORE DESC,
    FAVORITES DESC