SELECT T1.ID, T1.GENOTYPE, T2.GENOTYPE PARENT_GENOTYPE
FROM ECOLI_DATA T1 LEFT JOIN ECOLI_DATA T2
ON T1.PARENT_ID = T2.ID
WHERE T1.PARENT_ID IS NOT NULL
AND (T1.GENOTYPE & T2.GENOTYPE = T2.GENOTYPE)
ORDER BY 1;