SELECT
    ugb.TITLE as TITLE,
    ugb.BOARD_ID as BOARD_ID,
    ugr.REPLY_ID as REPLY_ID,
    ugr.WRITER_ID as WRITER_ID,
    ugr.CONTENTS as CONTENTS,
    DATE_FORMAT(ugr.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM
    USED_GOODS_BOARD as ugb
INNER JOIN
    USED_GOODS_REPLY as ugr
ON
    ugb.BOARD_ID = ugr.BOARD_ID
WHERE
    DATE_FORMAT(ugb.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY
    ugr.CREATED_DATE ASC,
    ugb.TITLE ASC
    