SELECT
    ID,
    CASE
        WHEN PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) <= 0.25 THEN 'CRITICAL'
        WHEN PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) <= 0.5 THEN 'HIGH'
        WHEN PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) <= 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
     END AS COLONY_NAME
FROM
    ECOLI_DATA
ORDER BY
    ID



# 윈도우 함수는 한 번만 쓰는 해답
WITH ranked AS (
  SELECT
    ID,
    PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS pr
  FROM ECOLI_DATA
)
SELECT
  ID,
  CASE
    WHEN pr <= 0.25 THEN 'CRITICAL'
    WHEN pr <= 0.50 THEN 'HIGH'
    WHEN pr <= 0.75 THEN 'MEDIUM'
    ELSE 'LOW'
  END AS COLONY_NAME
FROM ranked
ORDER BY ID;
