SELECT
    DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
    PRODUCT_ID,
    USER_ID,
    SALES_AMOUNT
FROM
    ONLINE_SALE
WHERE
    DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'
UNION ALL
SELECT
    DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
    PRODUCT_ID,
    NULL,
    SALES_AMOUNT
FROM
    OFFLINE_SALE
WHERE
    DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'
ORDER BY
    SALES_DATE,
    PRODUCT_ID,
    USER_ID

아래는 개선한 방향 (날짜 검색 시 아래처럼 해야 인덱스 적용 가능)
SELECT
  DATE_FORMAT(t.SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
  t.PRODUCT_ID,
  t.USER_ID,
  t.SALES_AMOUNT
FROM (
  SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
  FROM ONLINE_SALE
  WHERE SALES_DATE >= '2022-03-01' AND SALES_DATE < '2022-04-01'

  UNION ALL

  SELECT SALES_DATE, PRODUCT_ID, CAST(NULL AS SIGNED) AS USER_ID, SALES_AMOUNT
  FROM OFFLINE_SALE
  WHERE SALES_DATE >= '2022-03-01' AND SALES_DATE < '2022-04-01'
) AS t
ORDER BY t.SALES_DATE, t.PRODUCT_ID, t.USER_ID;
