SELECT
    p.PRODUCT_CODE,
    SUM(p.PRICE * os.SALES_AMOUNT) AS SALES
FROM
    OFFLINE_SALE AS os
INNER JOIN
    PRODUCT AS p
ON
    os.PRODUCT_ID = p.PRODUCT_ID
GROUP BY
    p.PRODUCT_CODE
ORDER BY
    SALES DESC,
    p.PRODUCT_CODE