SELECT
    fp.PRODUCT_ID,
    fp.PRODUCT_NAME,
    SUM(fo.AMOUNT) * fp.PRICE AS TOTAL_SALES
FROM
    FOOD_PRODUCT AS fp
INNER JOIN
    FOOD_ORDER AS fo
ON
    fp.PRODUCT_ID = fo.PRODUCT_ID
WHERE
    1=1
    AND fo.PRODUCE_DATE >= '2022-05-01'
    AND fo.PRODUCE_DATE < '2022-06-01'
GROUP BY
    fo.PRODUCT_ID
ORDER BY
    TOTAL_SALES DESC,
    fp.PRODUCT_ID