-- https://programmers.co.kr/learn/courses/30/lessons/59044
SELECT INS.NAME, INS.DATETIME
FROM ANIMAL_INS INS
LEFT OUTER JOIN ANIMAL_OUTS OUTS
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE OUTS.DATETIME IS NULL
ORDER BY INS.DATETIME
LIMIT 3

SELECT
    ai.NAME,
    ai.DATETIME
FROM
    ANIMAL_INS AS ai
LEFT OUTER JOIN
    ANIMAL_OUTS AS ao
ON
    ai.ANIMAL_ID = ao.ANIMAL_ID
WHERE
    ao.ANIMAL_ID IS NULL
ORDER BY
    ai.DATETIME
LIMIT 3