-- 코드를 입력하세요
SELECT INS.ANIMAL_ID, INS.NAME
FROM ANIMAL_INS INS
JOIN ANIMAL_OUTS OUTS
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE INS.DATETIME > OUTS.DATETIME
ORDER BY INS.DATETIME ASC;

SELECT
    ai.ANIMAL_ID,
    ai.NAME
FROM
    ANIMAL_INS AS ai
INNER JOIN
    ANIMAL_OUTS AS ao
ON
    ai.ANIMAL_ID = ao.ANIMAL_ID
WHERE
    ai.DATETIME > ao.DATETIME
ORDER BY
    ai.DATETIME