-- 1) 회원별 리뷰 수 집계
-- 2) 그 중 '최대 리뷰 수'와 같은 회원만 추려서
-- 3) 해당 회원들의 리뷰를 조회
SELECT
  m.MEMBER_NAME,
  r.REVIEW_TEXT,
  DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS m
JOIN REST_REVIEW AS r
  ON r.MEMBER_ID = m.MEMBER_ID
WHERE r.MEMBER_ID IN (
  SELECT MEMBER_ID
  FROM REST_REVIEW
  GROUP BY MEMBER_ID
  HAVING COUNT(*) = (
    SELECT MAX(cnt)
    FROM (SELECT COUNT(*) AS cnt
          FROM REST_REVIEW
          GROUP BY MEMBER_ID) AS x
  )
)
ORDER BY REVIEW_DATE, REVIEW_TEXT;
