WITH YEAR_AGGR AS (
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS `YEAR`,
        MAX(SIZE_OF_COLONY) AS YEAR_MAX
    FROM
        ECOLI_DATA
    GROUP BY
        YEAR(DIFFERENTIATION_DATE)
)
SELECT
    YEAR_AGGR.YEAR AS `YEAR`,
    (YEAR_AGGR.YEAR_MAX - ECOLI_DATA.SIZE_OF_COLONY) AS YEAR_DEV,
    ECOLI_DATA.ID AS ID
FROM
    ECOLI_DATA
INNER JOIN
    YEAR_AGGR
ON
    YEAR(ECOLI_DATA.DIFFERENTIATION_DATE) = YEAR_AGGR.YEAR
ORDER BY
    YEAR,
    YEAR_DEV