SELECT fi.ID, fni.FISH_NAME, fi.LENGTH
FROM FISH_INFO fi
JOIN FISH_NAME_INFO fni
  ON fi.FISH_TYPE = fni.FISH_TYPE
WHERE fi.LENGTH = (
  SELECT MAX(LENGTH) FROM FISH_INFO x
  WHERE x.FISH_TYPE = fi.FISH_TYPE
)
ORDER BY fi.ID;





WITH ranked AS (
  SELECT
    fi.ID,
    fni.FISH_NAME,
    fi.LENGTH,
    ROW_NUMBER() OVER (PARTITION BY fi.FISH_TYPE ORDER BY fi.LENGTH DESC) AS rn
  FROM FISH_INFO fi
  JOIN FISH_NAME_INFO fni
    ON fi.FISH_TYPE = fni.FISH_TYPE
)
SELECT ID, FISH_NAME, LENGTH
FROM ranked
WHERE rn = 1
ORDER BY ID;
