SELECT
    SUM(SCORE) AS SCORE, HG.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM
    HR_DEPARTMENT HD
    INNER JOIN HR_EMPLOYEES HE
        ON HD.DEPT_ID=HE.DEPT_ID
    INNER JOIN HR_GRADE HG
        ON HE.EMP_NO=HG.EMP_NO
WHERE 1=1
    AND YEAR = 2022
GROUP BY
    HG.EMP_NO
ORDER BY    
    SCORE DESC
LIMIT 1