-- 자기 자신을 parent로 가지는 아이템이 없는 아이템

SELECT 
    ITEM_ID,
    ITEM_NAME,
    RARITY
FROM ITEM_INFO
WHERE NOT EXISTS (
    SELECT 1
    FROM ITEM_TREE
    WHERE ITEM_INFO.ITEM_ID = ITEM_TREE.PARENT_ITEM_ID
)
ORDER BY
    ITEM_INFO.ITEM_ID DESC