WITH T AS (
    SELECT
        BOARD_ID
    FROM
        USED_GOODS_BOARD
    ORDER BY
        VIEWS DESC
    LIMIT 1
)
SELECT
    CONCAT('/home/grep/src/', T.BOARD_ID, '/', USED_GOODS_FILE.FILE_ID, USED_GOODS_FILE.FILE_NAME, USED_GOODS_FILE.FILE_EXT) AS FILE_PATH
FROM
    T
INNER JOIN
    USED_GOODS_FILE
ON
    T.BOARD_ID = USED_GOODS_FILE.BOARD_ID
ORDER BY
    USED_GOODS_FILE.FILE_ID DESC