SELECT
    b.INGREDIENT_TYPE,
    SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM
    FIRST_HALF AS a
INNER JOIN
    ICECREAM_INFO AS b
ON
    a.FLAVOR = b.FLAVOR
GROUP BY
    b.INGREDIENT_TYPE
ORDER BY
    SUM(TOTAL_ORDER)