SELECT
    DISTINCT cc.CAR_ID
FROM
    CAR_RENTAL_COMPANY_CAR AS cc
INNER JOIN
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS ch
ON
    cc.CAR_ID = ch.CAR_ID
WHERE
    1=1
    AND cc.CAR_TYPE = '세단'
    AND MONTH(ch.START_DATE) = 10
ORDER BY
    cc.CAR_ID DESC